<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Tzu-chi-market</title>
        <script src="<?= URL ?>public/js/vol-index.js"></script>
        <link rel="stylesheet" href="<?= URL ?>public/css/vol-index-page-styles.css" />
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@500&display=swap" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Caveat&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@1,600&display=swap" rel="stylesheet" />
        <script src="https://kit.fontawesome.com/64d58efce2.js" crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    </head>

    <body>
        <header>
            <div class="nav-bar">
                <div class="logo-container">
    
    
                    <div class="logo"></div>
                </div>
    
                <div class="title-name">
    
                    <h3 class="logo-name">
                        <div class="tzu-logo"></div>
                        Tzu Chi Foundation | <span> Hambantota</span>
                    </h3>
                </div>
    
                <div class="log-sign" style="--i: 1.8s;">
    
                    <a href="<?= URL ?>index" class="back-btn" alt="Sun"><i class="fas fa-home"></i></a>
                </div>
    
            </div>
    
        </header> 



        <div class="container">

            <div class="hd"></div>

            
            <div class="page-body">
                <div class="head-container">
                    
                    <div class="pg-name">
                        <h2>Welcome to Tzu-Chi Volunteers Module</h2>
                        <h3>Join Us !</h3>
                        <h4 style="font-family: 'Caveat', cursive;">
                          
                                    “Everybody can be great. Because anybody can serve. You don’t have to have a college degree to serve.
                                You don’t have to make your subject and your verb agree to serve.
                                You don’t have to know the second theory of thermodynamics in physics to serve.
                                You only need a heart full of grace. A soul generated by love.”
                                
                           
                            <span style="font-weight: bold; font-size:2.3vw;"> </Br> –Martin Luther King, Jr.</span>
                        </h4>
                        <div class="btns">
                            <a class="log" href="<?= URL ?>login?pf=vol">Log-In</a>
                            <a class="reg" href="<?= URL ?>register/index">Register</a>                       
                        </div>
                    </div>
                    <div class="home-img"><img src="<?= URL ?>public/images/vol-home-art.jpg"></div>
                
                </div>


                <div class="about">
                    <div class="img-slider">
                        <div class="slide active">
                            <img src="<?= URL ?>public/images/don1.jpg" alt="">
                            <div class="info">
                                <h2>Donation </h2>
                                <p>Staff & Volunteers working together</p>
                            </div>
                        </div>
                        <div class="slide">
                            <img src="<?= URL ?>public/images/volac3.jpeg" alt="">
                            <div class="info">
                                <h2>Team </h2>
                                <p>Visit for volunteer activity </p>
                            </div>
                        </div>
                        <div class="slide">
                            <img src="<?= URL ?>public/images/don3.jpg" alt="">
                            <div class="info">
                                <h2>Blood donation</h2>
                                <p>Give the gift of life!</p>
                            </div>
                        </div>
                        <div class="slide">
                            <img src="<?= URL ?>public/images/volac4.jpeg" alt="">
                            <div class="info">
                                <h2>Poster </h2>
                                <p>Blood Donation </p>
                            </div>
                        </div>
                        <div class="slide">
                            <img src="<?= URL ?>public/images/volac2.jpeg" alt="">
                            <div class="info">
                                <h2></h2>
                                <p></p>
                            </div>
                        </div>
                        <div class="navigation">
                            <div class="btn active"></div>
                            <div class="btn"></div>
                            <div class="btn"></div>
                            <div class="btn"></div>
                            <div class="btn"></div>
                        </div>
                    </div>

            <script type="text/javascript">
                var slides = document.querySelectorAll('.slide');
                var btns = document.querySelectorAll('.btn');
                let currentSlide = 1;

                // Javascript for image slider manual navigation
                var manualNav = function(manual){
                slides.forEach((slide) => {
                    slide.classList.remove('active');

                    btns.forEach((btn) => {
                    btn.classList.remove('active');
                    });
                });

                slides[manual].classList.add('active');
                btns[manual].classList.add('active');
                }

                btns.forEach((btn, i) => {
                btn.addEventListener("click", () => {
                    manualNav(i);
                    currentSlide = i;
                });
                });

                // Javascript for image slider autoplay navigation
                var repeat = function(activeClass){
                let active = document.getElementsByClassName('active');
                let i = 1;

                var repeater = () => {
                    setTimeout(function(){
                    [...active].forEach((activeSlide) => {
                        activeSlide.classList.remove('active');
                    });

                    slides[i].classList.add('active');
                    btns[i].classList.add('active');
                    i++;

                    if(slides.length == i){
                    i = 0;
                    }
                    if(i >= slides.length){
                    return;
                    }
                    repeater();
                }, 10000);
                }
                repeater();
                }
                repeat();
            </script>

                </div>

                
                
                <div class="media-container">
                    <div class="selection-panal">
                        <button class="h-btn" onclick="showAbout()">About us</button>  
                        <button class="h-btn" onclick="showAct()">Volunteering Activities</button>   
                        <button class="h-btn" onclick="showImg()">Images</button>
                        
                    </div>
                    <div class="about-us" id="aboutUs" style="display: block">
                        <div class="about-img-text">
                            <img src="<?= URL ?>public/images/tzuchilogo-temp.jpg">
                            <p>We are tzu-chi volunteers.tzu-chi foundation started in taiwan as a vision of master cheng yeng. we came to sri lanka after 2004 tzunami disaster and heplped
                                the victams to get back their feet. with the help of local donors and volunteers we still helping over 10000
                                people who need help.
                            </p>
                            
                        </div>
                        
                        
                        <h4>How to become a tzu-chi volunteer</h4>
                        
                        <p style="color:green;">Fill up the registration form with your details.</p>
                       
                        
                        <h4>Volunteer types of Tzu-Chi Foundation</h4>
                        <div class="images">

                            <div class="row">
                                <div class="vol-type-column">
                                    <div class="vol-cat-img">
                                        <img src="<?= URL ?>public/images/vol-yellow.jpg">
                                        <div class="text-box">
                                            <div class="vol-cat-name"><h3>Temporary Volunteers</h3></div>                                           
                                            <p>All people who want to serve for the organization can register and login the volunteer portal.Through his/her working times he/she hast to work for the 
                                                organization and earn points . </p>
                                        </div>
                                    </div>
                                </div>
                                <div class="vol-type-column">
                                    <div class="vol-cat-img">
                                        <img src="<?= URL ?>public/images/vol-gray.jpg">
                                        <div class="text-box">
                                            <div class="vol-cat-name"><h3>Permanent Volunteers</h3></div>                                           
                                            <p>While working as the Temporary volunteer he/she earn the limited points which branch choose, temporary Volunteer will be promoted as the 
                                                Permanent Volunteer. Permanant Volunteer can become staff if he/she works more for the Organization
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                
                            </div>  
                        </div>
                        <p style="color:green;">In Tzu-Chi, volunteers are rated according to their contribution to the volunteering activities.
                            All the new volunteers strts their journey as an yellow jacket volunteer. With their contributions
                            they can get gray and blue jackets.
                        </p>
                        <div class="images">
                            <div class="row">
                                <div class="jsy-type-column">
                                    <img src="<?= URL ?>public/images/yellow-temp.jpg">
                                    <h5>Yellow Colour Jursey of the temporary volunteers of tzu chi foundation</h4>
                                </div>
                                <div class="jsy-type-column">
                                    <img src="<?= URL ?>public/images/gray-temp.png">
                                    <h5>Gray Colour Jursey of the tzu chi foundation volunteers</h4>
                                </div>
                                <div class="jsy-type-column">
                                    <img src="<?= URL ?>public/images/blue-temp.png">
                                    <h5>Blue Colour Jursey of the permanent volunteers of tzu chi foundation</h4>
                                </div>
                            </div>
                        </div>
                        
                        
                        <h4>Volunteer points generating system</h4>
                        
                        <p style="color:green;">Earn more volunteer points by participating volunteer activities regularly.</p>

                   
                    </div>
                    <div class="vol-activities" id="volAct" style="display: none;">
                        <div class="about-img-text">
                        <p>we are conducting various volunteering activities through out the year.
                            any volunteer can join to them.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Hic est magni fugit esse provident. 
                            Magnam quos labore tempore eum corporis animi! Facilis animi laudantium corrupti odio quisquam, 
                            assumenda facere a.
                        </p>
                       
                        </div>

                        <div class="row">
                            <div class="vol-activities">
                                <div class="vol-act-list">
                                    <ul>
                                        <li><button class="vol-act-btns" onclick="displayBlodDonation()">Blood Donation </button></li>
                                        <li><button class="vol-act-btns" onclick="displayRecycing()">Collecting Recyclables </button></li>                                       
                                        <li><button class="vol-act-btns" onclick="displayHealthCamp()">Health Camps </button></li>
                                        <li><button class="vol-act-btns" onclick="displayTreePlanting()">Tree Planting Campaign </button></li>
                                        <li><button class="vol-act-btns" onclick="displayFoodDistribution()">Monthly Food Distributions </button></li>
                                        <li><button class="vol-act-btns"onclick="displayOtherActivities()">Other Volunteering Activities </button></li>
                                    </ul>

                                </div>
                                <div class="vol-act-dis">
                                    <div class="blod-donation" id="bold-donation" style="display:block;">
                                        <h4>Blod Donation Camp</h4>
                                        <img class="media-con-img" src="<?= URL ?>public/images/don3.jpg">
                                        <p style="color:green;">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Hic est magni fugit esse provident. 
                                        Magnam quos labore tempore eum corporis animi! Facilis animi laudantium corrupti odio quisquam, 
                                        assumenda facere a.</p>
                                    </div>
                                    <div class="collecting-rcb" id="collecting-rcb" style="display:none;">
                                        <h4>Collecting Recyclables</h4>
                                        <img class="media-con-img" src="<?= URL ?>public/images/recycling-temp.jpg">
                                        <p style="color:green;">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Hic est magni fugit esse provident. 
                                            Magnam quos labore tempore eum corporis animi! Facilis animi laudantium corrupti odio quisquam, 
                                            assumenda facere a.</p>

                                    </div>
                                    <div class="health-camp" id="health-camp" style="display:none;">
                                                    
                                        <h4>Health Camps</h4>
                                        <img class="media-con-img" src="<?= URL ?>public/images/health-camp-temp.jpg">
                                        <p style="color:green;">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Hic est magni fugit esse provident. 
                                            Magnam quos labore tempore eum corporis animi! Facilis animi laudantium corrupti odio quisquam, 
                                            assumenda facere a.</p>
                                    
                                    </div>
                                    <div class="tree-panting" id="tree-panting" style="display:none;">
                                        <h4>Tree Planting Campaign</h4>
                                        <img class="media-con-img" src="<?= URL ?>public/images/tree-planting-temp.jpg">
                                        <p style="color:green;">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Hic est magni fugit esse provident. 
                                            Magnam quos labore tempore eum corporis animi! Facilis animi laudantium corrupti odio quisquam, 
                                            assumenda facere a.</p>
                        
                                    </div>
                                    <div class="food-dis" id="food-dis" style="display:none;">
                                        <h4>Monthly Food Distributions</h4>
                                        <img class="media-con-img" src="<?= URL ?>public/images/food-distribution-temp.jpg">
                                        <p style="color:green;">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Hic est magni fugit esse provident. 
                                            Magnam quos labore tempore eum corporis animi! Facilis animi laudantium corrupti odio quisquam, 
                                            assumenda facere a.</p>

                                    </div>
                                    <div class="other-vol" id="other-vol" style="display:none;">
                                        other vol actvities
                                    </div>

                                </div>
                            </div>
                        </div>
                        
                    </div>
                    <div class="images" id="image-page" style="display: none;">
                        <div class="view-img">
                            <span onclick="this.parentElement.style.display='none'" class="close-btn">&times;</span>
                            <img id="bigImg" style="width:100%">
                            <div id="img-data"></div>
                        </div>
                        <div class="row">
                            <div class="column">
                                <img src="<?= URL ?>public/images/recy1.jpg" alt="Collecting recycled products. 2020-04-31" onclick="galleryViewImg(this)">
                            </div>
                            <div class="column">
                                <img src="<?= URL ?>public/images/recy2.jpg" alt="Collecting recycled products. 2020-04-31" onclick="galleryViewImg(this)">
                            </div>
                            <div class="column">
                                <img src="<?= URL ?>public/images/recy3.jpg" alt="Collecting recycled products. 2020-04-31" onclick="galleryViewImg(this)">
                            </div>
                            <div class="column">
                                <img src="<?= URL ?>public/images/recy1.jpg" alt="Collecting recycled products. 2020-04-31" onclick="galleryViewImg(this)">
                            </div>
                            <div class="column">
                                <img src="<?= URL ?>public/images/recy2.jpg" alt="Collecting recycled products. 2020-04-31" onclick="galleryViewImg(this)" >
                            </div>
                            <div class="column">
                                <img src="<?= URL ?>public/images/recy1.jpg" alt="Collecting recycled products. 2020-04-31" onclick="galleryViewImg(this)">
                            </div>
                            <div class="column">
                                <img src="<?= URL ?>public/images/recy1.jpg" alt="Collecting recycled products. 2020-04-31" onclick="galleryViewImg(this)">
                            </div>
                            <div class="column">
                                <img src="<?= URL ?>public/images/recy3.jpg" alt="Collecting recycled products. 2020-04-31" onclick="galleryViewImg(this)">
                            </div>
                            <div class="column">
                                <img src="<?= URL ?>public/images/recy2.jpg" alt="Collecting recycled products. 2020-04-31" onclick="galleryViewImg(this)">
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>



           
            
            




        <footer>
            <div class="footer">Powered by<h5>Humanity2020&copy;</div>
        </footer>    
    </body>

    
</html>